# Generated by Django 5.1.3 on 2024-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_time',
            field=models.CharField(max_length=255),
        ),
    ]
